const CONSTANTS = {
    "canvas_width":680,
    "canvas_height":480,
    "ball_start_x":310,
    "ball_start_y":406,
    "direction_right":"right",
    "direction_down":"down",
    "direction_up":"up",
    "direction_left":"left",
    "ball_size":64,
    "player_lives":3,
    "brick_size" : 33,
    "brick_width" : 68,
    "brick_height" : 34,
    "brick_offset" : 8,
    "paddle_start_x" : 290,
    "paddle_start_y" : 450,
    "paddle_x" : 0,
    "paddle_y" : 200,
    "paddle_width" : 100,
    "paddle_height" : 25
};